export default {
  // 组件被删除的时候
  COMPONENT_DELETE_ACTION: 'COMPONENT_DELETE_ACTION',

  // 组件被添加的时候
  COMPONENT_ADD_ACTION: 'COMPONENT_ADD_ACTION',

  // 组件过滤发生改变的时候
  COMPONENT_FILTER_CHANGE: 'COMPONENT_FILTER_CHANGE',

  // 组件拖拽开始
  COMPONENT_DRAG_START: 'COMPONENT_DRAG_START',

  // 组件拖拽
  COMPONENT_DRAG: 'COMPONENT_DRAG',

  // 组件拖拽结束
  COMPONENT_DRAG_END: 'COMPONENT_DRAG_END',

  // 组件缩放开始
  COMPONENT_RESIZE_START: 'COMPONENT_RESIZE_START',

  // 组件缩放
  COMPONENT_RESIZE: 'COMPONENT_RESIZE',

  // 组件缩放结束
  COMPONENT_RESIZE_END: 'COMPONENT_RESIZE_END',

  // 大屏的主题色被更改的时候
  SCREEN_THEME_CHANGE: 'SCREEN_THEME_CHANGE',

  // 图层被展示或收起的时候
  LAYER_VISIBLE_CHANGE: 'LAYER_VISIBLE_CHANGE',

  // 组件被hover时
  COMPONENT_HOVER_CHANGE: 'COMPONENT_HOVER_CHANGE',

  // 组件的idPathMap改变时
  COMPONENT_ID_PATH_MAP_CHANGE: 'COMPONENT_ID_PATH_MAP_CHANGE',

  // 图层hover
  LAYER_HOVER_CHANGE: 'LAYER_HOVER_CHANGE',

  // 组件搜索
  COMPONENT_SEARCH: 'COMPONENT_SEARCH',

  // 组件搜索框显示隐藏
  COMPONENT_SEARCH_VISIBLE: 'COMPONENT_SEARCH_VISIBLE',

  // 组件列表显示隐藏
  COMPONENT_LIST_VISIBLE: 'COMPONENT_LIST_VISIBLE',

  // 图层搜索
  LAYER_SEARCH: 'LAYER_SEARCH',

  // 组件选择
  COMPONENT_SELECT: 'COMPONENT_SELECT',

  // 组件数据请求（包括静态或mock）
  COMPONENT_REQUEST_DATA: 'COMPONENT_REQUEST_DATA',

  // 色调修改
  THEME_CHANGE: 'THEME_CHANGE',

  // 组的轮播配置的点击组件切换索引时
  GROUP_CAROUSEL_CLICK_INDEX_CHANGE: 'GROUP_CAROUSEL_CLICK_INDEX_CHANGE',

  // 组的轮播配置点击预览切换状态
  GROUP_CAROUSEL_CLICK_PREVIEW_CHANGE: 'GROUP_CAROUSEL_CLICK_PREVIEW_CHANGE',

  // 组轮播索引改变
  GROUP_CAROUSEL_INDEX_CHANGE: 'GROUP_CAROUSEL_INDEX_CHANGE',

  // 组轮播开始播放
  GROUP_CAROUSEL_START: 'GROUP_CAROUSEL_START',

  // 组轮播暂停播放
  GROUP_CAROUSEL_STOP: 'GROUP_CAROUSEL_STOP',

  // 本地配置 背景色
  CONFIG_KEY_BACKGROUND: 'CONFIG_KEY_BACKGROUND',

  // 本地配置 图层宽度
  CONFIG_KEY_LAYER_WIDTH: 'CONFIG_KEY_LAYER_WIDTH',

  // 本地配置 配置宽度
  CONFIG_KEY_COMPONENT_CONFIG_WIDTH: 'CONFIG_KEY_COMPONENT_CONFIG_WIDTH',

  // 本地配置 引导信息
  CONFIG_KEY_SHEPHERD_INFO: 'CONFIG_KEY_SHEPHERD_INFO',

  // 本地配置 主题设置引导信息
  CONFIG_KEY_SHEPHERD_THEME_CONFIG_INFO:
    'CONFIG_KEY_SHEPHERD_THEME_CONFIG_INFO',

  // 本地配置 跨tab复制
  CONFIG_KEY_CROSS_CLIPBOARD: 'CONFIG_KEY_CROSS_CLIPBOARD',

  // 本地配置 浏览器使用提醒
  CONFIG_KEY_CHROME_PROMPT: 'CONFIG_KEY_CHROME_PROMPT',

  // 本地配置 大屏图表数据存储
  STATIC_COMPONENT_DATA_SAVE_KEY: 'STATIC_COMPONENT_DATA_SAVE_KEY_KEY',

  // 本地配置 大屏数据存储时间戳
  STATIC_COMPONENT_DATA_SAVE_TIMESTAMPS:
    'STATIC_COMPONENT_DATA_SAVE_TIMESTAMPS',

  // 本地配置 大屏数据存储时间戳
  IMPROVE_BACKEND_STATIC_COMPONENT_DATA_SAVE_PREFIX:
    'IMPROVE_BACKEND_STATIC_COMPONENT_DATA_SAVE_PREFIX',

  // 本地配置 辅助线是否自动吸附整数坐标
  STATIC_GUIDE_LINE_DRAG_INTEGER_STICKY:
    'STATIC_GUIDE_LINE_DRAG_INTEGER_STICKY',

  // 静态版本大屏快照保存
  STATIC_SCREEN_SHOT_SAVE_KEY: 'STATIC_SCREEN_SHOT_SAVE_KEY',

  // 多选拖拽 开始拖拽
  MULTIPLE_COMPONENT_DRAG_START: 'MULTIPLE_COMPONENT_DRAG_START',

  // 多选拖拽 拖拽中
  MULTIPLE_COMPONENT_DRAG: 'MULTIPLE_COMPONENT_DRAG',

  // 多选拖拽 拖拽暂停
  MULTIPLE_COMPONENT_DRAG_STOP: 'MULTIPLE_COMPONENT_DRAG_STOP',

  // 多选缩放 开始缩放
  MULTIPLE_COMPONENT_RESIZE_START: 'MULTIPLE_COMPONENT_RESIZE_START',

  // 多选缩放 缩放中
  MULTIPLE_COMPONENT_RESIZE: 'MULTIPLE_COMPONENT_RESIZE',

  // 多选缩放 缩放暂停
  MULTIPLE_COMPONENT_RESIZE_STOP: 'MULTIPLE_COMPONENT_RESIZE_STOP',
};
